on: [push]

name: build

jobs:
  check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory

      - name: Check
        run: cargo check --release --locked
      - name: Build
        run: cargo build --locked
      - name: Run tests
        run: cargo test
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Clippy test
        run: cargo clippy --profile test -- -D warnings -D clippy::dbg_macro
